version: "3.9"
name: "flaskApp1"
services:
  web:
    build: web
    ports:
      - "56733:8000"
    volumes:
      - ./web:/app
    env_file:
      - .env.dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M